runtime: nodejs
env: flex
service: backend
entrypoint: npm start
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.80
env_variables:
  NOREPLY_USERNAME: $NOREPLY_USERNAME
  NOREPLY_PASSWORD: $NOREPLY_PASSWORD
  NOREPLY_HOST: $NOREPLY_HOST
  JWT_SECRET: $JWT_SECRET
  MONGODB_ATLAS_USER: $MONGODB_ATLAS_USER
  MONGODB_ATLAS_PASSWORD: $MONGODB_ATLAS_PASSWORD
  MONGODB_ATLAS_CLUSTER: $MONGODB_ATLAS_CLUSTER
  MONGODB_ATLAS_DBNAME: $MONGODB_ATLAS_DBNAME
  MONGODB_ATLAS_OPTIONS: $MONGODB_ATLAS_OPTIONS